logging.level.org.apache.ibatis: debug
logging.level.com.example.mybatis.mapper: trace
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username:
    password:
    url: jdbc:h2:file:./mybatis/database

mybatis:
  mapper-locations: classpath:mapper/*.xml